# Generated by Django 2.1.3 on 2018-11-24 14:49

import core.models
from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveygeneral',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='surveygeneral',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='surveygeneral',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='note',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='survey',
        ),
        migrations.AddField(
            model_name='survey',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='survey',
            name='business_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Business Name'),
        ),
        migrations.AddField(
            model_name='survey',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='survey',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='survey',
            name='cuit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CUIT'),
        ),
        migrations.AddField(
            model_name='survey',
            name='downtime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Downtime'),
        ),
        migrations.AddField(
            model_name='survey',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='survey',
            name='observations',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Observation'),
        ),
        migrations.AddField(
            model_name='survey',
            name='person_incharge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Person in charge'),
        ),
        migrations.AddField(
            model_name='survey',
            name='responsable',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='survey',
            name='tax_residence',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Residence'),
        ),
        migrations.AddField(
            model_name='survey',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='survey',
            name='webpage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Webpage'),
        ),
        migrations.AddField(
            model_name='survey',
            name='workhours',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Workhours'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(base_url='/media-private/', location='/home/javier/PycharmProjects/tesis/tesis/media/groups/'), upload_to=core.models.upload_backup, verbose_name='File'),
        ),
        migrations.DeleteModel(
            name='SurveyGeneral',
        ),
    ]
