# Generated by Django 2.1.3 on 2018-11-24 18:23

import core.models
from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181124_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='file',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(base_url='/media-private/', location='/home/javier/PycharmProjects/tesis/tesis/media/groups/'), upload_to=core.models.upload_backup, verbose_name='File'),
        ),
    ]
