# Generated by Django 2.1.3 on 2018-11-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181124_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyuser',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='surveyuser',
            name='last_name',
        ),
    ]
