# Generated by Django 2.1.3 on 2018-12-16 20:06

import core.models
from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181125_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(base_url='/group-private/', location='/home/javier/PycharmProjects/tesis/tesis/media/groups/'), upload_to=core.models.upload_backup, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guide',
            name='file',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(base_url='/group-private/', location='/home/javier/PycharmProjects/tesis/tesis/media/groups/'), upload_to=core.models.upload_guide, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='key',
            name='file',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(base_url='/group-private/', location='/home/javier/PycharmProjects/tesis/tesis/media/groups/'), upload_to=core.models.upload_key, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='file',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(base_url='/group-private/', location='/home/javier/PycharmProjects/tesis/tesis/media/groups/'), upload_to=core.models.upload_backup, verbose_name='File'),
        ),
    ]
