# Generated by Django 2.1.3 on 2019-02-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_set_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='qr',
            field=models.CharField(default='https://itmanager.site/qr_search/1', max_length=50, verbose_name='QR'),
        ),
    ]
