# Generated by Django 2.1.3 on 2019-02-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190204_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='qr',
            field=models.CharField(max_length=50, verbose_name='QR'),
        ),
    ]
