# Generated by Django 2.1.3 on 2019-02-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190207_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='set',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
