# Generated by Django 2.1.3 on 2019-02-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190207_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Note'),
        ),
    ]
