# Generated by Django 2.1.3 on 2019-02-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190209_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyworkstation',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Number'),
        ),
    ]
