# Generated by Django 2.1.3 on 2019-03-02 21:13

import core.models
from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190216_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(base_url='/group-private/', location='/home/ubuntu/tesis/media/group-private/'), upload_to=core.models.upload_backup, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='file',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(base_url='/group-private/', location='/home/ubuntu/tesis/media/group-private/'), upload_to=core.models.upload_guide, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='key',
            name='file',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(base_url='/group-private/', location='/home/ubuntu/tesis/media/group-private/'), upload_to=core.models.upload_key, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='file',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(base_url='/group-private/', location='/home/ubuntu/tesis/media/group-private/'), upload_to=core.models.upload_survey, verbose_name='File'),
        ),
    ]
