# Generated by Django 2.1.3 on 2019-01-02 02:49

from django.db import migrations
import private_storage.fields
import private_storage.storage.files
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20181226_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='file',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(base_url='/user-private/', location='/home/ubuntu/tesis/media/users/'), upload_to=registration.models.upload_key, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(base_url='/user-private/', location='/home/ubuntu/tesis/media/users/'), upload_to=registration.models.upload_note, verbose_name='File'),
        ),
    ]
