# Generated by Django 2.1.3 on 2019-02-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20190102_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkey',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='key',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='historicalkey',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='key',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Note'),
        ),
    ]
